#!/usr/bin/env python3
"""
HINEC tractography Design-Space Exploration (DSE) orchestrator.

WHAT IT DRIVES
--------------
The HINEC pipeline is preprocess-once / iterate-tractography. This tool drives the
tractography-only entry point:

    bin/run_tractography.sh <base_config> --score --set key=value ...

which is SYNCHRONOUS: for one cell it runs MATLAB tractography, converts tracks to TRK,
then runs the scilpy Renauld-2023 scorer, all in one blocking process, and prints
"Run dir:  hinec_runs/run_<ts>_<cfg><suffix>" to stdout. Output per cell:
    <run_dir>/tractography/tracks*.mat            (tracking done)
    <run_dir>/scoring/renauld2023/results.json    (scoring done -> mean_f1/mean_OL/...)

So a cell's PIPELINE STAGE is observable without cooperation from the child:
    run_dir missing              -> starting
    run_dir, no tracks*.mat      -> tracking
    tracks*.mat, no results.json -> scoring
    results.json present         -> done

DESIGN SPACE
------------
Every tractography parameter is `--set`-addressable, so the whole space is driven from
ONE controlled base config (dse_base.yml, written into the run dir). Each cell overrides
ONLY the axis under study; everything else is held fixed for a fair comparison.

    hinec:    field {dti,csd} x interp_method {trilinear,cubic}
              x sel_power {0,8,16,32} x integration_order {1,2,4,5}
    mmf:      field {dti,csd} x integrator {rk4,rkf45} x frame_sel_power {8,16,32}
    standard: FACT baseline (dti, Euler)

WHAT IT PRODUCES  (hinec_runs/dse_<ts>/)
    dse_base.yml    the controlled base config used by every cell
    manifest.json   the enumerated design space (immutable record of the run)
    status.json     live state of every cell (atomic writes; resume reads this)
    report.html     self-contained, auto-refreshing dashboard (view in any browser)
    logs/cell_<id>.log   combined stdout/stderr of each cell's run_tractography.sh

USAGE
    scripts/dse/dse.py plan   [--grid full|quick|smoke]
    scripts/dse/dse.py run    [--grid full|quick|smoke] [--parallel N] [--limit N]
                              [--dir PATH] [--refresh SECS] [--no-score]
    scripts/dse/dse.py report --dir hinec_runs/dse_<ts>
    scripts/dse/dse.py status --dir hinec_runs/dse_<ts>

Resume: `run --dir <existing dse dir>` re-reads status.json and only runs cells that are
not already `done`. stdlib-only; no third-party deps.
"""

import argparse
import json
import os
import re
import shlex
import signal
import subprocess
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]        # scripts/dse/dse.py -> repo root
RUN_TRACT = REPO_ROOT / "bin" / "run_tractography.sh"
DEFAULT_SOURCE = REPO_ROOT / "data" / "ismrm2015" / "ismrm2015.mat"

# --------------------------------------------------------------------------------------
# Controlled base config. Written into each DSE run dir; cells override ONLY swept axes.
# Every value here is held FIXED across all cells so a cell isolates one axis at a time.
# --------------------------------------------------------------------------------------
BASE_YAML = """# DSE controlled base config (auto-generated by scripts/dse/dse.py).
# NOT for production tracking: it exists so every DSE cell differs ONLY in the swept axis.
# The orchestrator overrides algorithm/field/interp_method/sel_power/integration_order/
# integrator/frame_sel_power per cell via --set; everything below is the fixed control.
preprocessing:
  denoise_method: 'dwidenoise'

tractography:
  # swept per cell (values here are placeholders)
  algorithm: 'hinec'
  field: 'dti'
  interp_method: 'trilinear'
  sel_power: 0
  integration_order: 5
  integrator: 'rk4'
  frame_sel_power: 16
  # fixed direction/integrator knobs
  adaptive_step: true
  rkf_tolerance: 0.02
  rkf_tol: 0.02
  mmf_anchor: 0
  # fixed control knobs (identical across ALL cells)
  seed_density: 8
  step_size: 0.2
  step_min: 0.02
  step_max: 0.5
  fa_threshold: 0.10
  termination_fa: 0.10
  angle_thresh: 45
  min_length: 15
  max_steps: 3000
  act_enabled: false
  # CSD FOD peak extraction (field=csd cells)
  csd_lmax: 6
  csd_max_peaks: 3
  csd_peak_thresh: 0.5
  csd_peak_min_sep: 45
"""

# --------------------------------------------------------------------------------------
# Design space
# --------------------------------------------------------------------------------------
GRIDS = {
    "full": {
        "hinec": {"field": ["dti", "csd"], "interp_method": ["trilinear", "cubic"],
                  "sel_power": [0, 8, 16, 32], "integration_order": [1, 2, 4, 5]},
        "mmf":   {"field": ["dti", "csd"], "interp_method": ["trilinear", "cubic"],
                  "integrator": ["rk4", "rkf45"], "frame_sel_power": [8, 16, 32]},
        "standard": {"field": ["dti"], "integration_order": [1]},
    },
    "quick": {
        "hinec": {"field": ["dti", "csd"], "interp_method": ["trilinear", "cubic"],
                  "sel_power": [0, 16], "integration_order": [4, 5]},
        "mmf":   {"field": ["dti", "csd"], "interp_method": ["trilinear", "cubic"],
                  "integrator": ["rk4", "rkf45"], "frame_sel_power": [16]},
        "standard": {"field": ["dti"], "integration_order": [1]},
    },
    "smoke": {  # 1 cell per algorithm — validates the whole plumbing fast
        "hinec": {"field": ["dti"], "interp_method": ["cubic"],
                  "sel_power": [16], "integration_order": [5]},
        "mmf":   {"field": ["dti"], "interp_method": ["trilinear"], "integrator": ["rk4"], "frame_sel_power": [16]},
        "standard": {"field": ["dti"], "integration_order": [1]},
    },
    "levers": {  # the frozen levers, at the best config (hinec dti cubic sp32 io5)
        "hinec": {"field": ["dti"], "interp_method": ["cubic"], "sel_power": [32],
                  "integration_order": [5],
                  "act_enabled": [0, 1], "termination_fa": [0.05, 0.10, 0.15, 0.20]},
    },
    "mmf_tune": {  # MMF-dedicated tuning: its own knobs, not the shared baseline
        "mmf": {"field": ["dti", "csd"], "interp_method": ["cubic"], "integrator": ["rk4", "rkf45"],
                "frame_sel_power": [16, 32],
                "mmf_anchor": [0.0, 0.3, 0.6], "termination_fa": [0.10, 0.15]},
    },
}

# Abbreviations for compact, stable cell ids
_INTERP_ABBR = {"trilinear": "tri", "cubic": "cub", "none": "none"}
_AXIS_ABBR = {"act_enabled": "act", "termination_fa": "tfa", "seed_density": "sd",
              "angle_thresh": "ang", "step_size": "ss", "min_length": "ml", "mmf_anchor": "anc"}
_STD_AXES = {"algorithm", "field", "interp_method", "sel_power",
             "integration_order", "integrator", "frame_sel_power"}


def _product(axes):
    """Cartesian product over an ordered dict of axis -> list-of-values."""
    keys = list(axes.keys())
    combos = [[]]
    for k in keys:
        combos = [c + [(k, v)] for c in combos for v in axes[k]]
    return [dict(c) for c in combos]


def build_cells(grid_name):
    """Enumerate the design space into a deterministic, ordered list of cell dicts."""
    grid = GRIDS[grid_name]
    cells = []
    for algo in ("standard", "hinec", "mmf"):
        if algo not in grid:
            continue
        for axes in _product(grid[algo]):
            overrides = {"algorithm": algo, **axes}
            cells.append({
                "id": _cell_id(algo, axes),
                "algorithm": algo,
                "field": axes.get("field", "dti"),
                "axes": axes,
                "overrides": overrides,
            })
    # de-dup (defensive) and keep enumeration order
    seen, out = set(), []
    for c in cells:
        if c["id"] in seen:
            continue
        seen.add(c["id"])
        out.append(c)
    return out


def _cell_id(algo, axes):
    if algo == "hinec":
        base = "hinec-{f}-{i}-sp{s}-io{o}".format(
            f=axes["field"], i=_INTERP_ABBR.get(axes["interp_method"], axes["interp_method"]),
            s=axes["sel_power"], o=axes["integration_order"])
    elif algo == "mmf":
        base = "mmf-{f}-{i}-{g}-fsp{s}".format(
            f=axes["field"], i=_INTERP_ABBR.get(axes["interp_method"], axes["interp_method"]),
            g=axes["integrator"], s=axes["frame_sel_power"])
    elif algo == "standard":
        base = "standard-{f}-io{o}".format(f=axes["field"], o=axes["integration_order"])
    else:
        base = algo
    # append any non-standard swept axes (e.g. act_enabled, termination_fa) so cells stay unique
    for k in sorted(k for k in axes if k not in _STD_AXES):
        v = axes[k]
        vs = ("1" if v else "0") if isinstance(v, bool) else str(v)
        base += "-{}{}".format(_AXIS_ABBR.get(k, k), vs)
    return base


# --------------------------------------------------------------------------------------
# Results parsing (defensive: scorer JSON shape is confirmed against the first real cell)
# --------------------------------------------------------------------------------------
def _flatten_numbers(obj, prefix=""):
    out = {}
    if isinstance(obj, dict):
        for k, v in obj.items():
            out.update(_flatten_numbers(v, f"{prefix}{k}."))
    elif isinstance(obj, (int, float)) and not isinstance(obj, bool):
        out[prefix.rstrip(".")] = float(obj)
    return out


def parse_results(run_dir):
    """Extract headline metrics from <run_dir>/scoring/renauld2023/results.json.
    Returns None if absent/unparsable. Defensive about exact key names."""
    if not run_dir:
        return None
    p = REPO_ROOT / run_dir / "scoring" / "renauld2023" / "results.json"
    if not p.exists():
        return None
    try:
        data = json.loads(p.read_text())
    except Exception:
        return None
    flat = _flatten_numbers(data)

    def pick(*names):
        for n in names:
            if n in flat:
                return flat[n]
        for n in names:
            for k, v in flat.items():
                if k.split(".")[-1] == n:
                    return v
        return None

    m = {
        "mean_f1":    pick("mean_f1", "f1", "mean_F1", "F1"),
        "mean_OL":    pick("mean_OL", "OL", "mean_ol", "mean_overlap"),
        "mean_OR_gt": pick("mean_OR_gt", "OR_gt", "mean_or_gt", "mean_overreach"),
        "mean_OR_vs": pick("mean_OR_vs"),
        "VB":         pick("VB", "valid_bundles", "vb"),
        "VS":         pick("VS", "vs"),                       # valid-streamline COUNT
        "VS_ratio":   pick("VS_ratio", "vs_ratio"),           # purity fraction (0..1)
        "IS_ratio":   pick("IS_ratio"),                       # invalid-streamline fraction
        "total_streamlines": pick("total_streamlines"),
    }
    return m


# --------------------------------------------------------------------------------------
# Orchestrator
# --------------------------------------------------------------------------------------
def now_iso():
    return datetime.now(timezone.utc).astimezone().isoformat(timespec="seconds")


def atomic_write(path: Path, text: str):
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(text)
    os.replace(tmp, path)


class Orchestrator:
    RUN_DIR_RE = re.compile(r"^Run dir:\s+(\S+)", re.MULTILINE)

    def __init__(self, dse_dir, cells, parallel, source, do_score, refresh, base_cfg,
                 workers, stagger, prune_trk=False, prune_mat=False):
        self.dir = dse_dir
        self.cells = {c["id"]: c for c in cells}
        self.order = [c["id"] for c in cells]
        self.parallel = parallel
        self.workers = workers                 # per-cell MATLAB parpool workers (HINEC_MAX_WORKERS)
        self.stagger = stagger                 # min seconds between cell launches (avoid parpool stampede)
        self.prune_trk = prune_trk             # delete scoring/tracks.trk after each cell scores (zero-loss)
        self.prune_mat = prune_mat             # also delete tractography/tracks*.mat (loses tractogram, keeps scores)
        self.source = source
        self.do_score = do_score
        self.refresh = refresh
        self.base_cfg = base_cfg
        self.logs = dse_dir / "logs"
        self.status_path = dse_dir / "status.json"
        self.report_path = dse_dir / "report.html"
        self.running = {}          # cell_id -> subprocess.Popen
        self.rt = {}               # cell_id -> {fh, t0}  (runtime handles; NEVER persisted)
        self.state = {}            # cell_id -> per-cell state dict (JSON-serializable only)
        self.stop = False
        self.started_at = now_iso()
        self._load_or_init_state()

    # ---- state ------------------------------------------------------------------
    def _load_or_init_state(self):
        prior = {}
        if self.status_path.exists():
            try:
                prior = json.loads(self.status_path.read_text()).get("cells", {})
            except Exception:
                prior = {}
        for cid in self.order:
            c = self.cells[cid]
            p = prior.get(cid)
            if p and p.get("state") == "done" and p.get("metrics"):
                self.state[cid] = p                     # keep finished cells on resume
            else:
                self.state[cid] = {
                    **{k: c[k] for k in ("id", "algorithm", "field", "axes")},
                    "state": "queued", "stage": "queued", "pid": None,
                    "run_dir": None, "log": os.path.relpath(self.logs / f"cell_{cid}.log", REPO_ROOT),
                    "cmd": None, "started": None, "finished": None,
                    "elapsed_s": None, "returncode": None, "metrics": None, "error": None,
                }

    def _pending(self):
        return [cid for cid in self.order if self.state[cid]["state"] == "queued"]

    def persist(self):
        summary = self._summary()
        doc = {
            "dse_id": self.dir.name, "started_at": self.started_at, "updated": now_iso(),
            "parallel": self.parallel, "source": str(self.source), "score": self.do_score,
            "base_config": str(self.base_cfg), "summary": summary,
            "cells": self.state,
        }
        atomic_write(self.status_path, json.dumps(doc, indent=2, default=str))
        atomic_write(self.report_path, render_html(doc, self.refresh))

    def _summary(self):
        by = {"queued": 0, "running": 0, "done": 0, "failed": 0}
        best = None
        elapsed = []
        for s in self.state.values():
            by[s["state"]] = by.get(s["state"], 0) + 1
            if s.get("elapsed_s"):
                elapsed.append(s["elapsed_s"])
            f1 = (s.get("metrics") or {}).get("mean_f1")
            if f1 is not None and (best is None or f1 > best["mean_f1"]):
                best = {"id": s["id"], "mean_f1": f1}
        total = len(self.state)
        finished = by.get("done", 0) + by.get("failed", 0)
        avg = sum(elapsed) / len(elapsed) if elapsed else None
        remaining = total - finished
        eta = None
        if avg and remaining:
            waves = -(-remaining // max(self.parallel, 1))     # ceil
            eta = round(avg * waves)
        return {"total": total, **by, "finished": finished,
                "avg_cell_s": round(avg) if avg else None, "eta_s": eta,
                "best": best}

    # ---- launching / monitoring -------------------------------------------------
    def _launch(self, cid):
        c = self.cells[cid]
        cmd = ["bash", str(RUN_TRACT), str(self.base_cfg), "--source", str(self.source)]
        if self.do_score:
            cmd.append("--score")
        for k, v in c["overrides"].items():
            cmd += ["--set", f"{k}={v}"]
        logf = self.logs / f"cell_{cid}.log"
        fh = open(logf, "w")
        # Per-cell MATLAB environment. A UNIQUE MATLAB_PREFDIR relocates each MATLAB's
        # local-cluster job storage, so concurrent cells' parpools cannot collide
        # (the "job not in pending state" race). HINEC_MAX_WORKERS caps each cell's pool.
        prefdir = self.dir / "mprefs" / cid
        prefdir.mkdir(parents=True, exist_ok=True)
        env = dict(os.environ)
        env["MATLAB_PREFDIR"] = str(prefdir)
        env["HINEC_MAX_WORKERS"] = str(self.workers)
        # own process group so we can tear down the whole tree (bash+matlab+python) cleanly
        proc = subprocess.Popen(cmd, cwd=str(REPO_ROOT), stdout=fh, stderr=subprocess.STDOUT,
                                start_new_session=True, env=env)
        self.running[cid] = proc
        self.rt[cid] = {"fh": fh, "t0": time.time()}   # runtime-only; not in self.state
        s = self.state[cid]
        s.update(state="running", stage="starting", pid=proc.pid, cmd=cmd, started=now_iso())
        print(f"[{now_iso()}] launch {cid}  pid={proc.pid}")

    def _find_run_dir(self, cid):
        logf = self.logs / f"cell_{cid}.log"
        try:
            m = self.RUN_DIR_RE.search(logf.read_text())
        except Exception:
            return None
        return m.group(1) if m else None

    def _detect_stage(self, cid, alive):
        s = self.state[cid]
        rd = s.get("run_dir")
        if rd is None:
            return "starting" if alive else s["stage"]
        rp = REPO_ROOT / rd
        if (rp / "scoring" / "renauld2023" / "results.json").exists():
            return "scoring" if alive else "done"
        if any((rp / "tractography").glob("tracks*.mat")):
            return "scoring" if self.do_score else "done"
        if rp.exists():
            return "tracking"
        return "starting"

    def _poll(self):
        for cid, proc in list(self.running.items()):
            s = self.state[cid]
            if s.get("run_dir") is None:
                s["run_dir"] = self._find_run_dir(cid)
            rc = proc.poll()
            if rc is None:
                s["stage"] = self._detect_stage(cid, alive=True)
                continue
            # finished
            rt = self.rt.pop(cid, {})
            if rt.get("fh"):
                rt["fh"].close()
            s["run_dir"] = s.get("run_dir") or self._find_run_dir(cid)
            metrics = parse_results(s["run_dir"])
            s["returncode"] = rc
            s["finished"] = now_iso()
            s["elapsed_s"] = round(time.time() - rt.get("t0", time.time()), 1)
            s["metrics"] = metrics
            self._prune(s["run_dir"])
            if rc == 0:
                s["state"], s["stage"] = "done", "done"
                if metrics is None:
                    s["error"] = "exit 0 but no results.json (scoring skipped/failed)"
            else:
                s["state"], s["stage"] = "failed", "failed"
                s["error"] = self._log_tail(cid)
            del self.running[cid]
            f1 = (metrics or {}).get("mean_f1")
            print(f"[{now_iso()}] {'done' if rc == 0 else 'FAIL'} {cid}  "
                  f"rc={rc} f1={f1} ({s['elapsed_s']}s)")

    def _log_tail(self, cid, n=25):
        try:
            lines = (self.logs / f"cell_{cid}.log").read_text().splitlines()
            return "\n".join(lines[-n:])
        except Exception:
            return None

    def _prune(self, run_dir):
        # After scoring, the .trk is pure scratch (regenerable from tracks.mat); optionally
        # the tracks.mat too. results.json / config / options are always kept.
        if not run_dir or not (self.prune_trk or self.prune_mat):
            return
        rd = REPO_ROOT / run_dir
        try:
            if self.prune_trk:
                trk = rd / "scoring" / "tracks.trk"
                if trk.exists():
                    trk.unlink()
            if self.prune_mat:
                for m in (rd / "tractography").glob("tracks*.mat"):
                    m.unlink()
        except Exception:
            pass

    def _teardown(self):
        for cid, proc in list(self.running.items()):
            try:
                os.killpg(os.getpgid(proc.pid), signal.SIGTERM)
            except Exception:
                pass
            self.state[cid].update(state="queued", stage="queued", pid=None)
            rt = self.rt.pop(cid, {})
            if rt.get("fh"):
                rt["fh"].close()
        self.running.clear()
        # MATLAB clients + parpool workers survive their launcher's death; reap any process
        # whose cmdline references this DSE dir (safe: this orchestrator's cmdline does not).
        try:
            subprocess.run(["pkill", "-9", "-f", str(self.dir.resolve())],
                           stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, timeout=15)
        except Exception:
            pass

    def run(self):
        def on_sig(signum, frame):
            print(f"\n[{now_iso()}] signal {signum} — stopping (running cells re-queued for resume)")
            self.stop = True
        signal.signal(signal.SIGINT, on_sig)
        signal.signal(signal.SIGTERM, on_sig)

        print(f"[{now_iso()}] DSE {self.dir.name}: {len(self.order)} cells, "
              f"parallel={self.parallel}, workers={self.workers}, stagger={self.stagger}s, "
              f"score={self.do_score}")
        self.persist()
        last_launch = 0.0
        try:
            while not self.stop:
                # Launch at most one cell per `stagger` seconds so concurrent parpools
                # never start simultaneously (a simultaneous stampede crashes MATLAB workers).
                now = time.time()
                if (len(self.running) < self.parallel and self._pending()
                        and now - last_launch >= self.stagger):
                    self._launch(self._pending()[0])
                    last_launch = time.time()
                self._poll()
                self.persist()
                if not self.running and not self._pending():
                    break
                time.sleep(2)
        finally:
            if self.stop:
                self._teardown()
            self.persist()
        s = self._summary()
        print(f"[{now_iso()}] DSE finished: done={s['done']} failed={s['failed']} "
              f"queued={s['queued']} best={s['best']}")
        return 0 if s.get("failed", 0) == 0 else 1


# --------------------------------------------------------------------------------------
# HTML report (self-contained, theme-aware, auto-refresh, client-side sort/filter)
# --------------------------------------------------------------------------------------
def render_html(doc, refresh, standalone=True):
    payload = json.dumps(doc).replace("</", "<\\/")
    refresh_meta = f'<meta http-equiv="refresh" content="{refresh}">' if refresh else ""
    head = (f'<!doctype html><html lang="en"><head><meta charset="utf-8">'
            f'<meta name="viewport" content="width=device-width,initial-scale=1">{refresh_meta}'
            f"<title>HINEC DSE — {doc['dse_id']}</title></head><body>") if standalone else ""
    tail = "</body></html>" if standalone else ""
    return f"""{head}<style>
:root {{ color-scheme: light dark;
  --bg:#f7f8fa; --fg:#1a1d21; --mut:#6b7280; --card:#fff; --line:#e5e7eb;
  --ok:#137333; --run:#1a56db; --fail:#b91c1c; --queue:#8a8f98; --accent:#5b3df5; }}
@media (prefers-color-scheme:dark) {{ :root {{
  --bg:#0e1013; --fg:#e6e8eb; --mut:#9aa1ab; --card:#171a1f; --line:#262a30;
  --ok:#4ade80; --run:#60a5fa; --fail:#f87171; --queue:#6b7280; --accent:#a78bfa; }} }}
*{{box-sizing:border-box}} body{{margin:0;background:var(--bg);color:var(--fg);
  font:14px/1.45 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif}}
.wrap{{max-width:1400px;margin:0 auto;padding:20px}}
h1{{font-size:18px;margin:0 0 2px}} .sub{{color:var(--mut);font-size:12px;margin-bottom:16px}}
.cards{{display:flex;flex-wrap:wrap;gap:12px;margin-bottom:16px}}
.card{{background:var(--card);border:1px solid var(--line);border-radius:10px;padding:12px 16px;min-width:120px}}
.card .k{{color:var(--mut);font-size:11px;text-transform:uppercase;letter-spacing:.04em}}
.card .v{{font-size:22px;font-weight:650;margin-top:2px}}
.bar{{height:8px;border-radius:6px;background:var(--line);overflow:hidden;margin:10px 0 18px}}
.bar > i{{display:block;height:100%;background:var(--accent)}}
.controls{{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:10px}}
.controls button{{background:var(--card);color:var(--fg);border:1px solid var(--line);
  border-radius:8px;padding:5px 10px;cursor:pointer;font-size:12px}}
.controls button.on{{border-color:var(--accent);color:var(--accent)}}
.tablewrap{{overflow-x:auto;background:var(--card);border:1px solid var(--line);border-radius:10px}}
table{{border-collapse:collapse;width:100%;font-size:13px;min-width:900px}}
th,td{{padding:7px 10px;text-align:left;border-bottom:1px solid var(--line);white-space:nowrap}}
th{{position:sticky;top:0;background:var(--card);cursor:pointer;user-select:none;font-weight:600}}
th:hover{{color:var(--accent)}} td.num,th.num{{text-align:right;font-variant-numeric:tabular-nums}}
tr:hover td{{background:rgba(127,127,127,.06)}}
.badge{{display:inline-block;padding:1px 8px;border-radius:20px;font-size:11px;font-weight:600}}
.b-done{{color:var(--ok);background:color-mix(in srgb,var(--ok) 15%,transparent)}}
.b-running{{color:var(--run);background:color-mix(in srgb,var(--run) 15%,transparent)}}
.b-failed{{color:var(--fail);background:color-mix(in srgb,var(--fail) 15%,transparent)}}
.b-queued{{color:var(--queue);background:color-mix(in srgb,var(--queue) 15%,transparent)}}
.f1cell{{position:relative;min-width:90px}}
.f1cell i{{position:absolute;left:0;top:0;bottom:0;background:color-mix(in srgb,var(--accent) 22%,transparent);z-index:0}}
.f1cell span{{position:relative;z-index:1;padding-left:2px}}
.best{{outline:2px solid var(--accent);outline-offset:-2px}}
a{{color:var(--accent);text-decoration:none}} a:hover{{text-decoration:underline}}
.mono{{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:11px;color:var(--mut)}}
.done-banner{{background:color-mix(in srgb,var(--ok) 14%,transparent);border:1px solid var(--ok);
  color:var(--ok);border-radius:8px;padding:8px 12px;margin-bottom:14px;font-weight:600}}
</style><div class="wrap">
<h1>HINEC Design-Space Exploration</h1>
<div class="sub" id="sub"></div>
<div id="banner"></div>
<div class="cards" id="cards"></div>
<div class="bar"><i id="progress"></i></div>
<div class="controls" id="filters"></div>
<div class="tablewrap"><table id="tbl"><thead><tr id="head"></tr></thead><tbody id="body"></tbody></table></div>
<div class="sub" style="margin-top:12px">Sorted client-side — click a header. Page auto-refreshes; data is embedded (works offline).</div>
</div>
<script id="data" type="application/json">{payload}</script>
<script>
const DOC = JSON.parse(document.getElementById('data').textContent);
const cells = Object.values(DOC.cells);
const S = DOC.summary || {{}};
const fmt = (x,d=3) => (x===null||x===undefined||Number.isNaN(x)) ? '' : (typeof x==='number'? x.toFixed(d): x);
const secs = s => s==null?'':(s>=3600?(s/3600).toFixed(1)+'h':s>=60?(s/60).toFixed(1)+'m':Math.round(s)+'s');
const met = (c,k) => (c.metrics && c.metrics[k]!=null) ? c.metrics[k] : null;

document.getElementById('sub').textContent =
  `${{DOC.dse_id}} · parallel ${{DOC.parallel}} · source ${{DOC.source}} · updated ${{DOC.updated}}`;
if (S.queued===0 && S.running===0)
  document.getElementById('banner').innerHTML = '<div class="done-banner">DSE COMPLETE — '+
    `${{S.done}} done, ${{S.failed}} failed${{S.best? ' · best F1 '+fmt(S.best.mean_f1)+' ('+S.best.id+')':''}}</div>`;

const cardDefs = [['total','cells'],['done','done'],['running','running'],['queued','queued'],
  ['failed','failed'],['avg_cell_s','avg/cell',secs],['eta_s','eta',secs]];
document.getElementById('cards').innerHTML = cardDefs.map(([k,label,f])=>
  `<div class="card"><div class="k">${{label}}</div><div class="v">${{f?f(S[k]):(S[k]??0)}}</div></div>`).join('')
  + (S.best? `<div class="card"><div class="k">best F1</div><div class="v">${{fmt(S.best.mean_f1)}}</div>`+
     `<div class="mono">${{S.best.id}}</div></div>`:'');
const prog = S.total? Math.round(100*(S.finished||0)/S.total):0;
document.getElementById('progress').style.width = prog+'%';

const COLS = [
  ['id','cell',c=>c.id,'l'],
  ['algorithm','algo',c=>c.algorithm,'l'],
  ['field','field',c=>c.field,'l'],
  ['interp','interp',c=>c.axes.interp_method||(c.algorithm==='standard'?'none':'trilinear'),'l'],
  ['traj','sel_pow',c=>c.axes.sel_power??c.axes.frame_sel_power??'','n'],
  ['integ','integrator',c=>c.axes.integration_order!=null?(c.axes.integration_order==1?'Euler':c.axes.integration_order==2?'RK2':c.axes.integration_order==4?'RK4':c.axes.integration_order==5?'RKF45':('io'+c.axes.integration_order)):(c.axes.integrator=='rk4'?'RK4':c.axes.integrator=='rkf45'?'RKF45':(c.axes.integrator||'')),'l'],
  ['state','state',c=>c.state,'l'],
  ['stage','stage',c=>c.stage,'l'],
  ['f1','F1',c=>met(c,'mean_f1'),'n'],
  ['ol','OL',c=>met(c,'mean_OL'),'n'],
  ['or','OR_gt',c=>met(c,'mean_OR_gt'),'n'],
  ['vs','VS%',c=>met(c,'VS_ratio'),'n'],
  ['vb','VB',c=>met(c,'VB'),'n'],
  ['elapsed','elapsed',c=>c.elapsed_s,'n'],
  ['pid','pid',c=>c.pid??'','n'],
  ['run','run_dir',c=>c.run_dir,'l'],
];
const maxF1 = Math.max(0.0001, ...cells.map(c=>met(c,'mean_f1')||0));
const bestId = S.best? S.best.id : null;
let sortKey='f1', sortDir=-1, filt='all';

document.getElementById('head').innerHTML = COLS.map(([k,label,,align])=>
  `<th class="${{align==='n'?'num':''}}" data-k="${{k}}">${{label}}</th>`).join('');
document.querySelectorAll('#head th').forEach(th=>th.onclick=()=>{{
  const k=th.dataset.k; sortDir = (sortKey===k)? -sortDir : (['f1','ol','vs','vb','elapsed'].includes(k)?-1:1);
  sortKey=k; render();
}});

const algos=['all',...new Set(cells.map(c=>c.algorithm))];
const states=['all','done','running','queued','failed'];
document.getElementById('filters').innerHTML =
  [...algos,...states].map(x=>`<button data-f="${{x}}" class="${{x==='all'?'on':''}}">${{x}}</button>`).join('');
document.querySelectorAll('#filters button').forEach(b=>b.onclick=()=>{{
  filt=b.dataset.f; document.querySelectorAll('#filters button').forEach(x=>x.classList.toggle('on',x===b)); render();
}});

function valOf(c,k){{ const col=COLS.find(x=>x[0]===k); let v=col?col[2](c):null;
  return (v===''||v==null)? (['f1','ol','or','vs','vb','elapsed','traj','pid'].includes(k)?-Infinity:'') : v; }}
function render(){{
  let rows=cells.slice();
  if(filt!=='all') rows=rows.filter(c=>c.algorithm===filt||c.state===filt);
  rows.sort((a,b)=>{{const x=valOf(a,sortKey),y=valOf(b,sortKey);
    return (x<y?-1:x>y?1:0)*sortDir;}});
  document.getElementById('body').innerHTML = rows.map(c=>{{
    const f1=met(c,'mean_f1'); const w=f1?Math.round(100*f1/maxF1):0;
    return `<tr class="${{c.id===bestId?'best':''}}">`+COLS.map(([k,,get,align])=>{{
      if(k==='f1'){{ return `<td class="num f1cell">${{f1!=null?`<i style="width:${{w}}%"></i><span>${{fmt(f1)}}</span>`:''}}</td>`; }}
      if(k==='state') return `<td><span class="badge b-${{c.state}}">${{c.state}}</span></td>`;
      let v=get(c);
      if(['ol','or'].includes(k)) v=fmt(v);
      if(k==='vs') v=(v==null?'':(v*100).toFixed(1)+'%');
      if(k==='vb'&&v!=null) v=Math.round(v);
      if(k==='elapsed') v=secs(v);
      if(k==='run'&&v) v=`<span class="mono">${{v.replace('hinec_runs/','')}}</span>`;
      return `<td class="${{align==='n'?'num':''}}">${{v==null?'':v}}</td>`;
    }}).join('')+`</tr>`;
  }}).join('');
}}
render();
</script>{tail}"""


# --------------------------------------------------------------------------------------
# LIVE served dashboard (polls status.json via fetch; in-place updates, no reload).
# Served by `dse.py serve` behind HTTP Basic auth; front with cloudflared or ssh -L.
# --------------------------------------------------------------------------------------
_LIVE_TEMPLATE = """<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1"><title>__TITLE__</title>
<style>
:root { color-scheme: light dark;
  --bg:#f7f8fa; --fg:#1a1d21; --mut:#6b7280; --card:#fff; --line:#e5e7eb;
  --ok:#137333; --run:#1a56db; --fail:#b91c1c; --queue:#8a8f98; --accent:#5b3df5; }
@media (prefers-color-scheme:dark) { :root {
  --bg:#0e1013; --fg:#e6e8eb; --mut:#9aa1ab; --card:#171a1f; --line:#262a30;
  --ok:#4ade80; --run:#60a5fa; --fail:#f87171; --queue:#6b7280; --accent:#a78bfa; } }
*{box-sizing:border-box} body{margin:0;background:var(--bg);color:var(--fg);
  font:14px/1.45 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif}
.wrap{max-width:1400px;margin:0 auto;padding:20px}
h1{font-size:18px;margin:0 0 2px} .sub{color:var(--mut);font-size:12px;margin-bottom:16px}
.cards{display:flex;flex-wrap:wrap;gap:12px;margin-bottom:16px}
.card{background:var(--card);border:1px solid var(--line);border-radius:10px;padding:12px 16px;min-width:120px}
.card .k{color:var(--mut);font-size:11px;text-transform:uppercase;letter-spacing:.04em}
.card .v{font-size:22px;font-weight:650;margin-top:2px}
.bar{height:8px;border-radius:6px;background:var(--line);overflow:hidden;margin:10px 0 18px}
.bar > i{display:block;height:100%;background:var(--accent);transition:width .4s}
.controls{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:10px}
.controls button{background:var(--card);color:var(--fg);border:1px solid var(--line);
  border-radius:8px;padding:5px 10px;cursor:pointer;font-size:12px}
.controls button.on{border-color:var(--accent);color:var(--accent)}
.fgroup{display:flex;align-items:center;gap:4px;flex-wrap:wrap;flex-basis:100%}
.flabel{color:var(--mut);font-size:11px;text-transform:uppercase;letter-spacing:.04em;min-width:78px}
.tablewrap{overflow-x:auto;background:var(--card);border:1px solid var(--line);border-radius:10px}
table{border-collapse:collapse;width:100%;font-size:13px;min-width:900px}
th,td{padding:7px 10px;text-align:left;border-bottom:1px solid var(--line);white-space:nowrap}
th{position:sticky;top:0;background:var(--card);cursor:pointer;user-select:none;font-weight:600}
th:hover{color:var(--accent)} td.num,th.num{text-align:right;font-variant-numeric:tabular-nums}
tr:hover td{background:rgba(127,127,127,.06)}
.badge{display:inline-block;padding:1px 8px;border-radius:20px;font-size:11px;font-weight:600}
.b-done{color:var(--ok);background:color-mix(in srgb,var(--ok) 15%,transparent)}
.b-running{color:var(--run);background:color-mix(in srgb,var(--run) 15%,transparent)}
.b-failed{color:var(--fail);background:color-mix(in srgb,var(--fail) 15%,transparent)}
.b-queued{color:var(--queue);background:color-mix(in srgb,var(--queue) 15%,transparent)}
.f1cell{position:relative;min-width:90px}
.f1cell i{position:absolute;left:0;top:0;bottom:0;background:color-mix(in srgb,var(--accent) 22%,transparent);z-index:0}
.f1cell span{position:relative;z-index:1;padding-left:2px}
.best{outline:2px solid var(--accent);outline-offset:-2px}
.mono{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:11px;color:var(--mut)}
.done-banner{background:color-mix(in srgb,var(--ok) 14%,transparent);border:1px solid var(--ok);
  color:var(--ok);border-radius:8px;padding:8px 12px;margin-bottom:14px;font-weight:600}
.live{display:inline-block;width:8px;height:8px;border-radius:50%;background:var(--ok);margin-right:6px;vertical-align:middle}
.live.off{background:var(--fail)}
</style></head><body><div class="wrap">
<h1>HINEC Design-Space Exploration</h1>
<div class="sub"><span class="live" id="live"></span><span id="conn">connecting…</span></div>
<div id="banner"></div>
<div class="cards" id="cards"></div>
<div class="bar"><i id="progress"></i></div>
<div class="controls" id="filters"></div>
<div class="tablewrap"><table id="tbl"><thead><tr id="head"></tr></thead><tbody id="body"></tbody></table></div>
<div class="sub" style="margin-top:12px">Live — polls status.json every __INTERVAL_S__s. Click a header to sort; sort/filter persist across updates.</div>
</div>
<script>
const fmt=(x,d=3)=>(x===null||x===undefined||Number.isNaN(x))?'':(typeof x==='number'?x.toFixed(d):x);
const secs=s=>s==null?'':(s>=3600?(s/3600).toFixed(1)+'h':s>=60?(s/60).toFixed(1)+'m':Math.round(s)+'s');
const met=(c,k)=>(c.metrics&&c.metrics[k]!=null)?c.metrics[k]:null;
let cells=[], S={}, sortKey='f1', sortDir=-1, sel={}, filtersBuilt=false;
const COLS=[
  ['id','cell',c=>c.id],['algorithm','algo',c=>c.algorithm],['field','field',c=>c.field],
  ['interp','interp',c=>c.axes.interp_method||(c.algorithm==='standard'?'none':'trilinear')],
  ['traj','sel_pow',c=>c.axes.sel_power??c.axes.frame_sel_power??''],
  ['integ','integrator',c=>c.axes.integration_order!=null?(c.axes.integration_order==1?'Euler':c.axes.integration_order==2?'RK2':c.axes.integration_order==4?'RK4':c.axes.integration_order==5?'RKF45':('io'+c.axes.integration_order)):(c.axes.integrator=='rk4'?'RK4':c.axes.integrator=='rkf45'?'RKF45':(c.axes.integrator||''))],
  ['act','ACT',c=>c.axes.act_enabled==null?'':(c.axes.act_enabled?'on':'off')],
  ['tfa','term_fa',c=>c.axes.termination_fa??''],
  ['state','state',c=>c.state],['stage','stage',c=>c.stage],
  ['f1','F1',c=>met(c,'mean_f1')],['ol','OL',c=>met(c,'mean_OL')],['or','OR_gt',c=>met(c,'mean_OR_gt')],['orv','OR_vs',c=>met(c,'mean_OR_vs')],
  ['vs','VS%',c=>met(c,'VS_ratio')],['is','IS%',c=>met(c,'IS_ratio')],['vb','VB',c=>met(c,'VB')],
  ['vsn','VS#',c=>met(c,'VS')],['nstr','nstream',c=>met(c,'total_streamlines')],['elapsed','elapsed',c=>c.elapsed_s],
  ['pid','pid',c=>c.pid??''],['run','run_dir',c=>c.run_dir]];
const NUM=new Set(['traj','tfa','f1','ol','or','orv','vs','is','vb','vsn','nstr','elapsed','pid']);
document.getElementById('head').innerHTML=COLS.map(([k,label])=>`<th class="${NUM.has(k)?'num':''}" data-k="${k}">${label}</th>`).join('');
document.querySelectorAll('#head th').forEach(th=>th.onclick=()=>{const k=th.dataset.k;sortDir=(sortKey===k)?-sortDir:(['f1','ol','vs','vb','elapsed'].includes(k)?-1:1);sortKey=k;render();});
const integName=c=>c.axes.integration_order!=null?(c.axes.integration_order==1?'Euler':c.axes.integration_order==2?'RK2':c.axes.integration_order==4?'RK4':c.axes.integration_order==5?'RKF45':('io'+c.axes.integration_order)):(c.axes.integrator=='rk4'?'RK4':c.axes.integrator=='rkf45'?'RKF45':(c.axes.integrator||'—'));
const AXES=[['algorithm','algo',c=>c.algorithm],['field','field',c=>c.field],['interp','interp',c=>c.axes.interp_method||(c.algorithm==='standard'?'none':'trilinear')],['sel_pow','sel_pow',c=>String(c.axes.sel_power??c.axes.frame_sel_power??'—')],['integrator','integrator',integName],['act','ACT',c=>c.axes.act_enabled==null?'—':(c.axes.act_enabled?'on':'off')],['tfa','term_fa',c=>String(c.axes.termination_fa??'—')],['state','state',c=>c.state]];
function buildFilters(){
  document.getElementById('filters').innerHTML=AXES.map(([key,label,get])=>{
    const vals=[...new Set(cells.map(get))].sort((a,b)=>(a==='—'?1:b==='—'?-1:(''+a).localeCompare(''+b,undefined,{numeric:true})));
    return `<div class="fgroup"><span class="flabel">${label}</span>`+['all',...vals].map(v=>`<button data-ax="${key}" data-v="${v}" class="${(sel[key]===undefined&&v==='all')||sel[key]===v?'on':''}">${v}</button>`).join('')+`</div>`;
  }).join('')+`<div class="fgroup"><span class="flabel"></span><span class="sub" id="matched" style="margin:0"></span></div>`;
  document.querySelectorAll('#filters button').forEach(b=>b.onclick=()=>{
    const ax=b.dataset.ax,v=b.dataset.v; if(v==='all')delete sel[ax];else sel[ax]=v;
    document.querySelectorAll('#filters button[data-ax="'+ax+'"]').forEach(x=>x.classList.toggle('on',(sel[ax]===undefined&&x.dataset.v==='all')||sel[ax]===x.dataset.v));
    render();
  });
}
function update(doc){
  cells=Object.values(doc.cells||{}); S=doc.summary||{};
  if(!filtersBuilt&&cells.length){buildFilters();filtersBuilt=true;}
  document.getElementById('banner').innerHTML=(S.queued===0&&S.running===0&&cells.length)?
    `<div class="done-banner">DSE COMPLETE — ${S.done} done, ${S.failed} failed${S.best?' · best F1 '+fmt(S.best.mean_f1)+' ('+S.best.id+')':''}</div>`:'';
  const cd=[['total','cells'],['done','done'],['running','running'],['queued','queued'],['failed','failed'],['avg_cell_s','avg/cell',secs],['eta_s','eta',secs]];
  document.getElementById('cards').innerHTML=cd.map(([k,label,f])=>`<div class="card"><div class="k">${label}</div><div class="v">${f?f(S[k]):(S[k]??0)}</div></div>`).join('')+(S.best?`<div class="card"><div class="k">best F1</div><div class="v">${fmt(S.best.mean_f1)}</div><div class="mono">${S.best.id}</div></div>`:'');
  document.getElementById('progress').style.width=(S.total?Math.round(100*(S.finished||0)/S.total):0)+'%';
  render();
}
function valOf(c,k){const col=COLS.find(x=>x[0]===k);let v=col?col[2](c):null;return (v===''||v==null)?(NUM.has(k)?-Infinity:''):v;}
function render(){
  const maxF1=Math.max(0.0001,...cells.map(c=>met(c,'mean_f1')||0));const bestId=S.best?S.best.id:null;
  let rows=cells.slice();
  for(const [k,,get] of AXES){if(sel[k]!==undefined)rows=rows.filter(c=>get(c)===sel[k]);}
  const M=document.getElementById('matched');
  if(M)M.textContent=`showing ${rows.length} of ${cells.length}`+(Object.keys(sel).length?` · ${Object.entries(sel).map(([k,v])=>k+'='+v).join(', ')}`:'');
  rows.sort((a,b)=>{const x=valOf(a,sortKey),y=valOf(b,sortKey);return (x<y?-1:x>y?1:0)*sortDir;});
  document.getElementById('body').innerHTML=rows.map(c=>{
    const f1=met(c,'mean_f1');const w=f1?Math.round(100*f1/maxF1):0;
    return `<tr class="${c.id===bestId?'best':''}">`+COLS.map(([k,,get])=>{
      if(k==='f1')return `<td class="num f1cell">${f1!=null?`<i style="width:${w}%"></i><span>${fmt(f1)}</span>`:''}</td>`;
      if(k==='state')return `<td><span class="badge b-${c.state}">${c.state}</span></td>`;
      let v=get(c);
      if(['ol','or','orv'].includes(k))v=fmt(v);
      if(['vs','is'].includes(k))v=(v==null?'':(v*100).toFixed(1)+'%');
      if(['vb','vsn','nstr'].includes(k)&&v!=null)v=Math.round(v).toLocaleString();
      if(k==='elapsed')v=secs(v);
      if(k==='run'&&v)v=`<span class="mono">${v.replace('hinec_runs/','')}</span>`;
      return `<td class="${NUM.has(k)?'num':''}">${v==null?'':v}</td>`;
    }).join('')+`</tr>`;
  }).join('');
}
function conn(ok,ts){document.getElementById('live').className='live'+(ok?'':' off');document.getElementById('conn').textContent=ok?('live · updated '+(ts||'')):'reconnecting…';}
async function tick(){try{const r=await fetch('status.json',{cache:'no-store'});if(!r.ok)throw 0;const doc=await r.json();update(doc);conn(true,doc.updated||'');}catch(e){conn(false);}}
tick();setInterval(tick,__INTERVAL_MS__);
</script></body></html>"""


def render_live_page(interval):
    return (_LIVE_TEMPLATE
            .replace("__INTERVAL_MS__", str(int(interval * 1000)))
            .replace("__INTERVAL_S__", str(int(interval)))
            .replace("__TITLE__", "HINEC Tractography DSE"))


def cmd_serve(args):
    import base64
    import secrets
    from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
    d = Path(args.dir)
    status_path = d / "status.json"
    if not status_path.exists():
        print(f"error: no status.json in {d}", file=sys.stderr)
        return 2
    require_auth = not args.no_auth
    user = args.user
    pw = args.password or secrets.token_urlsafe(9)
    token = base64.b64encode(f"{user}:{pw}".encode()).decode()
    page = render_live_page(args.interval).encode()

    class Handler(BaseHTTPRequestHandler):
        def _authed(self):
            return (not require_auth) or self.headers.get("Authorization", "") == f"Basic {token}"

        def do_GET(self):
            if not self._authed():
                self.send_response(401)
                self.send_header("WWW-Authenticate", 'Basic realm="HINEC DSE"')
                self.send_header("Content-Length", "0")
                self.end_headers()
                return
            path = self.path.split("?")[0]
            if path in ("/", "/index.html"):
                body, ctype = page, "text/html; charset=utf-8"
            elif path == "/status.json":
                try:
                    body = status_path.read_bytes()
                except Exception:
                    body = b"{}"
                ctype = "application/json"
            else:
                self.send_response(404)
                self.send_header("Content-Length", "0")
                self.end_headers()
                return
            self.send_response(200)
            self.send_header("Content-Type", ctype)
            self.send_header("Cache-Control", "no-store")
            self.send_header("Content-Length", str(len(body)))
            self.end_headers()
            self.wfile.write(body)

        def log_message(self, *a):
            pass  # quiet

    srv = ThreadingHTTPServer((args.host, args.port), Handler)
    if require_auth:
        print(f"[serve] {d.name} at http://{args.host}:{args.port}  (HTTP Basic auth)")
        print(f"[serve] user: {user}")
        print(f"[serve] pass: {pw}")
    else:
        print(f"[serve] {d.name} at http://{args.host}:{args.port}  (NO AUTH)")
    sys.stdout.flush()
    try:
        srv.serve_forever()
    except KeyboardInterrupt:
        pass
    return 0


# --------------------------------------------------------------------------------------
# CLI
# --------------------------------------------------------------------------------------
def cmd_plan(args):
    cells = build_cells(args.grid)
    by = {}
    for c in cells:
        by[c["algorithm"]] = by.get(c["algorithm"], 0) + 1
    print(f"grid '{args.grid}': {len(cells)} cells  " +
          "  ".join(f"{k}={v}" for k, v in by.items()))
    for c in cells:
        print(f"  {c['id']:32s}  " + " ".join(f"{k}={v}" for k, v in c['overrides'].items()))
    return 0


def _new_dir():
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    d = REPO_ROOT / "hinec_runs" / f"dse_{ts}"
    return d


def cmd_run(args):
    cells = build_cells(args.grid)
    if args.limit:
        cells = cells[:args.limit]
    dse_dir = Path(args.dir).resolve() if args.dir else _new_dir()
    dse_dir.mkdir(parents=True, exist_ok=True)
    (dse_dir / "logs").mkdir(exist_ok=True)
    base_cfg = dse_dir / "dse_base.yml"
    if not base_cfg.exists():
        base_cfg.write_text(BASE_YAML)
    atomic_write(dse_dir / "manifest.json", json.dumps(
        {"grid": args.grid, "created": now_iso(), "parallel": args.parallel,
         "score": not args.no_score, "cells": cells}, indent=2))
    source = Path(args.source).resolve() if args.source else DEFAULT_SOURCE
    if not source.exists():
        print(f"error: source nim not found: {source}", file=sys.stderr)
        return 2
    orch = Orchestrator(dse_dir, cells, parallel=args.parallel, source=source,
                        do_score=not args.no_score, refresh=args.refresh, base_cfg=base_cfg,
                        workers=args.workers, stagger=args.stagger,
                        prune_trk=args.prune_trk, prune_mat=args.prune_mat)
    print(f"DSE dir: {dse_dir}")
    print(f"report : {dse_dir / 'report.html'}")
    return orch.run()


def cmd_report(args):
    d = Path(args.dir)
    doc = json.loads((d / "status.json").read_text())
    atomic_write(d / "report.html", render_html(doc, args.refresh))
    print(f"wrote {d / 'report.html'}")
    return 0


def cmd_status(args):
    doc = json.loads((Path(args.dir) / "status.json").read_text())
    s = doc["summary"]
    print(f"{doc['dse_id']}  updated {doc['updated']}")
    print(f"  total {s['total']}  done {s['done']}  running {s['running']}  "
          f"queued {s['queued']}  failed {s['failed']}")
    if s.get("best"):
        print(f"  best F1 {s['best']['mean_f1']:.4f}  ({s['best']['id']})")
    if s.get("eta_s"):
        print(f"  eta ~{s['eta_s']}s  (avg/cell {s.get('avg_cell_s')}s)")
    for cid, c in doc["cells"].items():
        if c["state"] == "running":
            print(f"  running {cid:32s} stage={c['stage']} pid={c['pid']} run={c['run_dir']}")
    return 0


def main():
    ap = argparse.ArgumentParser(description="HINEC tractography DSE orchestrator")
    sub = ap.add_subparsers(dest="cmd", required=True)

    p = sub.add_parser("plan", help="enumerate the design space and exit")
    p.add_argument("--grid", choices=list(GRIDS), default="full")
    p.set_defaults(func=cmd_plan)

    p = sub.add_parser("run", help="run the DSE (long-running)")
    p.add_argument("--grid", choices=list(GRIDS), default="full")
    p.add_argument("--parallel", type=int, default=6, help="max concurrent MATLAB cells")
    p.add_argument("--workers", type=int, default=8, help="parpool workers per cell (HINEC_MAX_WORKERS)")
    p.add_argument("--stagger", type=int, default=12, help="min seconds between cell launches (anti-stampede)")
    p.add_argument("--prune-trk", action="store_true", help="delete scoring/tracks.trk after each cell scores (zero-loss)")
    p.add_argument("--prune-mat", action="store_true", help="also delete tracks*.mat after scoring (keeps results.json)")
    p.add_argument("--limit", type=int, default=0, help="run only the first N cells (validation)")
    p.add_argument("--dir", default="", help="reuse/resume an existing dse_<ts> dir")
    p.add_argument("--source", default="", help="preprocessed nim (default data/ismrm2015/ismrm2015.mat)")
    p.add_argument("--refresh", type=int, default=20, help="report auto-refresh seconds (0=off)")
    p.add_argument("--no-score", action="store_true", help="track only, skip scoring")
    p.set_defaults(func=cmd_run)

    p = sub.add_parser("report", help="regenerate report.html from status.json")
    p.add_argument("--dir", required=True)
    p.add_argument("--refresh", type=int, default=20)
    p.set_defaults(func=cmd_report)

    p = sub.add_parser("status", help="print a live status summary")
    p.add_argument("--dir", required=True)
    p.set_defaults(func=cmd_status)

    p = sub.add_parser("serve", help="serve a LIVE auth-gated dashboard (front with cloudflared/ssh -L)")
    p.add_argument("--dir", required=True)
    p.add_argument("--host", default="127.0.0.1", help="bind host (127.0.0.1 = localhost only)")
    p.add_argument("--port", type=int, default=8787)
    p.add_argument("--interval", type=float, default=5, help="client poll seconds")
    p.add_argument("--user", default="hinec", help="HTTP Basic auth username")
    p.add_argument("--password", default="", help="HTTP Basic auth password (random if omitted)")
    p.add_argument("--no-auth", action="store_true", help="disable HTTP Basic auth (open dashboard)")
    p.set_defaults(func=cmd_serve)

    args = ap.parse_args()
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
